name: Gradle CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        type: string
        default: '25'
      gradle-command:
        description: 'Gradle command to run'
        required: false
        type: string
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # 6.0.2

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@b622de1dfa918ecc0ab28f40cd42e3c3752cd6c5 # 5.2.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@11d4d83c63a6ce61b32d8a9c4faddbdb04fe9917 # 6.1.0

      - name: Run Gradle ${{ inputs.gradle-command }}
        run: ./gradlew ${{ inputs.gradle-command }}